### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by jmgurney** [hyansuper/wsmprpc#4]
Without a license, this code is not [legally] usable by anyone.

Please add a license file.

I'd recommend either a BSD or MIT license, or possibly the Apache as it includes JS code that people will need to integrate into their application.

**Comment by jmgurney** [comment]
So, I notice that you tagged the `setup.py` w/ MIT, but as that doesn't include the text, I'm not confident that would hold up legally in someone's defense.  I'd recommend including at a minimum the license file, but better would be to include it in each file.

**Comment by hyansuper** [comment]
Thanks, previsly I thought the code is totally free if not stated otherwise
